### ISSUE TITLE
Release for melodic

### ISSUE THREAD

**Issue by hrnr** [ros-gbp/opencv3-release#17] opened 2018-05-17 18:38 UTC
Hi,

what are the plans for melodic? Are there plans to release this package everywhere to pull in the right version of the OpenCV or should we use `cv_bridge` and `image_geometry` instead as per http://wiki.ros.org/opencv3#package.xml? If the `opencv3` will be missing in melodic this should be mentioned on http://wiki.ros.org/melodic/Migration.

Does it mean also that we will be missing `opencv_contrib` again?

Cheers,
Jiri

**Comment by tfoote** [comment] 2018-05-17 22:28
Duplicate of #16 We'll be recommending the system version of opencv. See https://github.com/ros-infrastructure/rep/pull/160 and http://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023

Contrib has been packaged for a long time and is a dependency of the full `libopencv-dev` package https://packages.ubuntu.com/en/bionic/libopencv-dev which is the rosdep

https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L2329

I've also mentioned to use the rosdep rule in the Migration guide.

**Closed as completed by tfoote** 2018-05-17 22:28 UTC
